import bcrypt from 'bcryptjs';
import prisma from '../lib/prisma';
import dotenv from 'dotenv';
dotenv.config();

import crypto from 'crypto';

async function main() {
  const username = process.argv[2] || process.env.ADMIN_INIT_USERNAME || 'admin';
  const customPassword = process.argv[3] || process.env.ADMIN_INIT_PASSWORD;
  const isAutoGenerated = !customPassword;
  const password = customPassword || crypto.randomBytes(8).toString('hex');

  console.log(`Setting up admin user: "${username}"...`);

  const existing = await prisma.admin.findUnique({ where: { username } });
  const hashedPassword = await bcrypt.hash(password, 10);

  if (existing) {
    await prisma.admin.update({
      where: { username },
      data: { password: hashedPassword }
    });
    console.log(`✅ Admin "${username}" berhasil diupdate.`);
  } else {
    await prisma.admin.create({
      data: { username, password: hashedPassword }
    });
    console.log(`✅ Admin "${username}" berhasil dibuat.`);
  }

  if (isAutoGenerated) {
    console.log(`🔑 PASSWORD GENERATED: ${password}`);
    console.log(`⚠️  Simpan password di atas untuk login pertama kali, lalu ganti melalui panel admin!`);
  }
}

main()
  .catch((e) => {
    console.error('❌ Error seeding admin:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
